### ISSUE TITLE
[gateway] inconsistent counters detected - please report to developer

### ISSUE THREAD

**Issue by JackDaniel007** [iobroker-community-adapters/ioBroker.envertech-pv#44] opened 2023-03-30 08:46 UTC
`<html>
<body>

envertech-pv.0 | Zeit | info | Nachricht
-- | -- | -- | --
envertech-pv.0 | 2023-03-30 10:45:39.431 | warn | [gateway] TotalCount: 2, cvtOnline:1, cvtOffline:0
envertech-pv.0 | 2023-03-30 10:45:39.430 | warn | [gateway] inconsistent counters detected - please report to developer
envertech-pv.0 | 2023-03-30 10:45:08.391 | info | scanning started for 1 station(s)
envertech-pv.0 | 2023-03-30 10:45:08.387 | info | [start] scanning station with id AABD69538AB5FC4A86B419C0C7162F571EZZ
envertech-pv.0 | 2023-03-30 10:45:07.783 | info | starting. Version 1.0.1 (non-npm: iobroker-community-adapters/ioBroker.envertech-pv#602972b55ac4b328bbceb16a4ccb855c95a0968e) in /opt/iobroker/node_modules/iobroker.envertech-pv, node: v18.15.0, js-controller: 4.0.24
envertech-pv.0 | 2023-03-30 10:45:00.016 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
envertech-pv.0 | 2023-03-30 10:45:00.016 | info | terminating
envertech-pv.0 | 2023-03-30 10:45:00.014 | warn | Got terminate signal. Checking desired PID: 0 vs own PID 3543
envertech-pv.0 | 2023-03-30 10:44:12.786 | warn | [gateway] TotalCount: 2, cvtOnline:1, cvtOffline:0
envertech-pv.0 | 2023-03-30 10:44:12.786 | warn | [gateway] inconsistent counters detected - please report to developer
envertech-pv.0 | 2023-03-30 10:43:34.483 | warn | [gateway] TotalCount: 2, cvtOnline:1, cvtOffline:0
envertech-pv.0 | 2023-03-30 10:43:34.482 | warn | [gateway] inconsistent counters detected - please report to developer

</body>
</html>`

**Comment by mcm1957** [comment] 2023-03-30 18:45
Thanks for reporting. 
The message indicates that the website reported 2 converters as total number of convertes while looping over the detail records only listed 1 converter. Could be envertech or adapter problem. I'll investigate further.

Could you please state whts the correct number of microconverters attached to you system. The number of converters you see at website). Are those micro converters connecte to one or multiple gateways?

The problem was persistent at least during the time of log. Does it still exist or is / was it a spourios problem?

Did the adapter create states for all of your converters or is one or more converters missing?
Are the values reported at states ok or are some values suspect?

What is the value for all ST-xxx.GW-xxxx.CVTxxxx.STATUS ? Especially at the time the problem exists.

If possible activate Option "Enable logging of http requests.", let the system operform one or two scans and send the http response data to me - either as attachment her or per PN (mcm57@gmx.at). Please check that no sensitive data (Passwords etc) is stored within this data.

Sorry that I have more questions than answer at the moment.

**Comment by JackDaniel007** [comment] 2023-03-31 05:59
Could you please state whts the correct number of microconverters attached to you system. The number of converters you see at website). Are those micro converters connecte to one or multiple gateways?

* 1 x EVT 300 u. 1 x EVT 560 connected with 1 x EVB 300

The problem was persistent at least during the time of log. Does it still exist or is / was it a spourios problem?
* comes with every query of the data 

Did the adapter create states for all of your converters or is one or more converters missing?
* both are present, data points also

Are the values reported at states ok or are some values suspect?
* looks good so far, what is missing is the total savings of money

What is the value for all ST-xxx.GW-xxxx.CVTxxxx.STATUS ? Especially at the time the problem exists.
* EVT 560 = 0, EVT 300 = 2


envertech-pv.0
2023-03-31 07:57:11.784	info	[RESPONSE] status 200 - {"Status":"0","Result":null,"Data":{"QueryResults":[{"GATEWAYALIAS":"Enverbridge","GATEWAYSN":"94000936","SNALIAS":"Südost","SN":"20139780","DCVOLTAGE":"24.19","ACVOLTAGE":"240.64","ACCURRENCY":"0","POWER":"4.77","FREQUENCY":"50.01","DAYENERGY":"0","ENERGY":"274.63","TEMPERATURE":"14.7","SITETIME":"3/31/2023 7:56:43 AM","STATIONID":null,"STATUS":"0","SNID":"694780013BF84365AE48CB74EC2F8A28"},{"GATEWAYALIAS":"Enverbridge","GATEWAYSN":"94000936","SNALIAS":"Südwest","SN":"12893962","DCVOLTAGE":"21.84","ACVOLTAGE":"241.08","ACCURRENCY":"0","POWER":"0","FREQUENCY":"50.01","DAYENERGY":"0","ENERGY":"101.24","TEMPERATURE":"12.7","SITETIME":"3/31/2023 7:56:43 AM","STATIONID":null,"STATUS":"0","SNID":"8DB6DA9AF183478BB023CF4CF0CC2687"}],"PageNumber":1,"PerPage":20,"TotalPage":1,"TotalCount":2,"Lan":"en-us"}}

envertech-pv.0
2023-03-31 07:57:04.481	info	[REQUEST ] https://www.envertecportal.com/ApiInverters/QueryTerminalReal?page=1&perPage=20&orderBy=GATEWAYSN&whereCondition=%7B%22STATIONID%22%3A%22BD69538AB5FC4A86B419C0C7162F571E%22%7D

envertech-pv.0
2023-03-31 07:57:04.360	info	[RESPONSE] status 200 - {"Status":"0","Result":null,"Data":{"UnitCapacity":"0.9 kWp","UnitEToday":"0 kWh","UnitEMonth":"21.02 kWh","UnitEYear":"62.41 kWh","UnitETotal":"375.87 kWh","Power":4.77,"PowerStr":"4.77 W","Capacity":0.9,"StrCO2":"0.375 ton","StrTrees":"2","StrIncome":"€ 169.14","PwImg":"133212851848601888_23.png","StationName":"DaHam","InvModel1":null,"InvModel2":null,"Lat":46.77477477477478,"Lng":13.549004453344937,"TimeZone":2,"StrPeakPower":"344.09 W","Installer":"Ich","CreateTime":"27/08/2021 GMT +2","CreateYear":2021,"CreateMonth":8,"Etoday":0,"InvTotal":2}}

envertech-pv.0
2023-03-31 07:57:03.211	info	[REQUEST ] https://www.envertecportal.com/ApiStations/getStationInfo?stationId=BD69538AB5FC4A86B419C0C7162F571E

envertech-pv.0
2023-03-31 07:56:05.188	warn	[gateway] TotalCount: 2, cvtOnline:1, cvtOffline:0

envertech-pv.0
2023-03-31 07:56:05.188	warn	[gateway] inconsistent counters detected - please report to developer

envertech-pv.0
2023-03-31 07:56:05.014	info	[RESPONSE] status 200 - {"Status":"0","Result":null,"Data":{"QueryResults":[{"GATEWAYALIAS":"Enverbridge","GATEWAYSN":"94000936","SNALIAS":"Südost","SN":"20139780","DCVOLTAGE":"24.1","ACVOLTAGE":"241.23","ACCURRENCY":"0","POWER":"2.73","FREQUENCY":"50.03","DAYENERGY":"0","ENERGY":"274.63","TEMPERATURE":"14.2","SITETIME":"3/31/2023 7:54:30 AM","STATIONID":null,"STATUS":"0","SNID":"694780013BF84365AE48CB74EC2F8A28"},{"GATEWAYALIAS":"Enverbridge","GATEWAYSN":"94000936","SNALIAS":"Südwest","SN":"12893962","DCVOLTAGE":"21.39","ACVOLTAGE":"241.33","ACCURRENCY":"0","POWER":"0","FREQUENCY":"50.02","DAYENERGY":"0","ENERGY":"101.24","TEMPERATURE":"12.7","SITETIME":"3/31/2023 7:54:30 AM","STATIONID":null,"STATUS":"2","SNID":"8DB6DA9AF183478BB023CF4CF0CC2687"}],"PageNumber":1,"PerPage":20,"TotalPage":1,"TotalCount":2,"Lan":"en-us"}}

envertech-pv.0
2023-03-31 07:56:03.800	info	[REQUEST ] https://www.envertecportal.com/ApiInverters/QueryTerminalReal?page=1&perPage=20&orderBy=GATEWAYSN&whereCondition=%7B%22STATIONID%22%3A%22BD69538AB5FC4A86B419C0C7162F571E%22%7D

envertech-pv.0
2023-03-31 07:56:03.391	info	[RESPONSE] status 200 - {"Status":"0","Result":null,"Data":{"UnitCapacity":"0.9 kWp","UnitEToday":"0 kWh","UnitEMonth":"21.02 kWh","UnitEYear":"62.41 kWh","UnitETotal":"375.87 kWh","Power":2.73,"PowerStr":"2.73 W","Capacity":0.9,"StrCO2":"0.375 ton","StrTrees":"2","StrIncome":"€ 169.14","PwImg":"133212851848601888_23.png","StationName":"DaHam","InvModel1":null,"InvModel2":null,"Lat":46.77477477477478,"Lng":13.549004453344937,"TimeZone":2,"StrPeakPower":"344.09 W","Installer":"Ich","CreateTime":"27/08/2021 GMT +2","CreateYear":2021,"CreateMonth":8,"Etoday":0,"InvTotal":2}}

envertech-pv.0
2023-03-31 07:56:03.210	info	[REQUEST ] https://www.envertecportal.com/ApiStations/getStationInfo?stationId=BD69538AB5FC4A86B419C0C7162F571E

envertech-pv.0
2023-03-31 07:55:34.051	warn	[gateway] TotalCount: 2, cvtOnline:1, cvtOffline:0

envertech-pv.0
2023-03-31 07:55:34.050	warn	[gateway] inconsistent counters detected - please report to developer

envertech-pv.0
2023-03-31 07:55:33.508	info	[RESPONSE] status 200 - {"Status":"0","Result":null,"Data":{"QueryResults":[{"GATEWAYALIAS":"Enverbridge","GATEWAYSN":"94000936","SNALIAS":"Südost","SN":"20139780","DCVOLTAGE":"24.1","ACVOLTAGE":"241.23","ACCURRENCY":"0","POWER":"2.73","FREQUENCY":"50.03","DAYENERGY":"0","ENERGY":"274.63","TEMPERATURE":"14.2","SITETIME":"3/31/2023 7:54:30 AM","STATIONID":null,"STATUS":"0","SNID":"694780013BF84365AE48CB74EC2F8A28"},{"GATEWAYALIAS":"Enverbridge","GATEWAYSN":"94000936","SNALIAS":"Südwest","SN":"12893962","DCVOLTAGE":"21.39","ACVOLTAGE":"241.33","ACCURRENCY":"0","POWER":"0","FREQUENCY":"50.02","DAYENERGY":"0","ENERGY":"101.24","TEMPERATURE":"12.7","SITETIME":"3/31/2023 7:54:30 AM","STATIONID":null,"STATUS":"2","SNID":"8DB6DA9AF183478BB023CF4CF0CC2687"}],"PageNumber":1,"PerPage":20,"TotalPage":1,"TotalCount":2,"Lan":"en-us"}}

envertech-pv.0
2023-03-31 07:55:33.304	info	[REQUEST ] https://www.envertecportal.com/ApiInverters/QueryTerminalReal?page=1&perPage=20&orderBy=GATEWAYSN&whereCondition=%7B%22STATIONID%22%3A%22BD69538AB5FC4A86B419C0C7162F571E%22%7D

envertech-pv.0
2023-03-31 07:55:33.302	info	[RESPONSE] error: AxiosError: timeout of 30000ms exceeded}

envertech-pv.0
2023-03-31 07:55:03.210	info	[REQUEST ] https://www.envertecportal.com/ApiStations/getStationInfo?stationId=BD69538AB5FC4A86B419C0C7162F571E

envertech-pv.0
2023-03-31 07:55:03.208	info	scanning started for 1 station(s)

envertech-pv.0
2023-03-31 07:55:03.207	info	[start] scanning station with id BD69538AB5FC4A86B419C0C7162F571E

envertech-pv.0
2023-03-31 07:55:02.744	info	starting. Version 1.0.1 (non-npm: iobroker-community-adapters/ioBroker.envertech-pv#602972b55ac4b328bbceb16a4ccb855c95a0968e) in /opt/iobroker/node_modules/iobroker.envertech-pv, node: v18.15.0, js-controller: 4.0.24

envertech-pv.0
2023-03-31 07:55:00.010	info	Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason

envertech-pv.0
2023-03-31 07:55:00.009	info	terminating

envertech-pv.0
2023-03-31 07:55:00.008	warn	Got terminate signal. Checking desired PID: 0 vs own PID 60236

envertech-pv.0
2023-03-31 07:54:03.850	info	[RESPONSE] status 200 - {"Status":"0","Result":null,"Data":{"QueryResults":[{"GATEWAYALIAS":"Enverbridge","GATEWAYSN":"94000936","SNALIAS":"Südost","SN":"20139780","DCVOLTAGE":"23.84","ACVOLTAGE":"240.36","ACCURRENCY":"0","POWER":"1.34","FREQUENCY":"50.02","DAYENERGY":"0","ENERGY":"274.63","TEMPERATURE":"13.7","SITETIME":"3/31/2023 7:52:18 AM","STATIONID":null,"STATUS":"0","SNID":"694780013BF84365AE48CB74EC2F8A28"},{"GATEWAYALIAS":"Enverbridge","GATEWAYSN":"94000936","SNALIAS":"Südwest","SN":"12893962","DCVOLTAGE":"20.48","ACVOLTAGE":"241.7","ACCURRENCY":"0","POWER":"0","FREQUENCY":"50.03","DAYENERGY":"0","ENERGY":"101.24","TEMPERATURE":"12.4","SITETIME":"3/31/2023 7:52:18 AM","STATIONID":null,"STATUS":"0","SNID":"8DB6DA9AF183478BB023CF4CF0CC2687"}],"PageNumber":1,"PerPage":20,"TotalPage":1,"TotalCount":2,"Lan":"en-us"}}

envertech-pv.0
2023-03-31 07:54:03.697	info	[REQUEST ] https://www.envertecportal.com/ApiInverters/QueryTerminalReal?page=1&perPage=20&orderBy=GATEWAYSN&whereCondition=%7B%22STATIONID%22%3A%22BD69538AB5FC4A86B419C0C7162F571E%22%7D

envertech-pv.0
2023-03-31 07:54:03.577	info	[RESPONSE] status 200 - {"Status":"0","Result":null,"Data":{"UnitCapacity":"0.9 kWp","UnitEToday":"0 kWh","UnitEMonth":"21.02 kWh","UnitEYear":"62.41 kWh","UnitETotal":"375.87 kWh","Power":1.34,"PowerStr":"1.34 W","Capacity":0.9,"StrCO2":"0.375 ton","StrTrees":"2","StrIncome":"€ 169.14","PwImg":"133212851848601888_23.png","StationName":"DaHam","InvModel1":null,"InvModel2":null,"Lat":46.77477477477478,"Lng":13.549004453344937,"TimeZone":2,"StrPeakPower":"344.09 W","Installer":"Ich","CreateTime":"27/08/2021 GMT +2","CreateYear":2021,"CreateMonth":8,"Etoday":0,"InvTotal":2}}

envertech-pv.0
2023-03-31 07:54:03.227	info	[REQUEST ] https://www.envertecportal.com/ApiStations/getStationInfo?stationId=BD69538AB5FC4A86B419C0C7162F571E

envertech-pv.0
2023-03-31 07:53:34.503	info	[RESPONSE] status 200 - {"Status":"0","Result":null,"Data":{"QueryResults":[{"GATEWAYALIAS":"Enverbridge","GATEWAYSN":"94000936","SNALIAS":"Südost","SN":"20139780","DCVOLTAGE":"23.84","ACVOLTAGE":"240.36","ACCURRENCY":"0","POWER":"1.34","FREQUENCY":"50.02","DAYENERGY":"0","ENERGY":"274.63","TEMPERATURE":"13.7","SITETIME":"3/31/2023 7:52:18 AM","STATIONID":null,"STATUS":"0","SNID":"694780013BF84365AE48CB74EC2F8A28"},{"GATEWAYALIAS":"Enverbridge","GATEWAYSN":"94000936","SNALIAS":"Südwest","SN":"12893962","DCVOLTAGE":"20.48","ACVOLTAGE":"241.7","ACCURRENCY":"0","POWER":"0","FREQUENCY":"50.03","DAYENERGY":"0","ENERGY":"101.24","TEMPERATURE":"12.4","SITETIME":"3/31/2023 7:52:18 AM","STATIONID":null,"STATUS":"0","SNID":"8DB6DA9AF183478BB023CF4CF0CC2687"}],"PageNumber":1,"PerPage":20,"TotalPage":1,"TotalCount":2,"Lan":"en-us"}}

envertech-pv.0
2023-03-31 07:53:33.242	info	[REQUEST ] https://www.envertecportal.com/ApiInverters/QueryTerminalReal?page=1&perPage=20&orderBy=GATEWAYSN&whereCondition=%7B%22STATIONID%22%3A%22BD69538AB5FC4A86B419C0C7162F571E%22%7D

envertech-pv.0
2023-03-31 07:53:33.231	info	[RESPONSE] error: AxiosError: timeout of 30000ms exceeded}

envertech-pv.0
2023-03-31 07:53:03.227	info	[REQUEST ] https://www.envertecportal.com/ApiStations/getStationInfo?stationId=BD69538AB5FC4A86B419C0C7162F571E

envertech-pv.0
2023-03-31 07:52:10.828	warn	[gateway] TotalCount: 2, cvtOnline:1, cvtOffline:0

envertech-pv.0
2023-03-31 07:52:10.828	warn	[gateway] inconsistent counters detected - please report to developer

envertech-pv.0
2023-03-31 07:52:10.676	info	[RESPONSE] status 200 - {"Status":"0","Result":null,"Data":{"QueryResults":[{"GATEWAYALIAS":"Enverbridge","GATEWAYSN":"94000936","SNALIAS":"Südost","SN":"20139780","DCVOLTAGE":"23.8","ACVOLTAGE":"240.63","ACCURRENCY":"0","POWER":"0.33","FREQUENCY":"50.01","DAYENERGY":"0","ENERGY":"274.63","TEMPERATURE":"13.2","SITETIME":"3/31/2023 7:50:05 AM","STATIONID":null,"STATUS":"0","SNID":"694780013BF84365AE48CB74EC2F8A28"},{"GATEWAYALIAS":"Enverbridge","GATEWAYSN":"94000936","SNALIAS":"Südwest","SN":"12893962","DCVOLTAGE":"19.25","ACVOLTAGE":"240.84","ACCURRENCY":"0","POWER":"0","FREQUENCY":"50","DAYENERGY":"0","ENERGY":"101.24","TEMPERATURE":"12.4","SITETIME":"3/31/2023 7:50:05 AM","STATIONID":null,"STATUS":"2","SNID":"8DB6DA9AF183478BB023CF4CF0CC2687"}],"PageNumber":1,"PerPage":20,"TotalPage":1,"TotalCount":2,"Lan":"en-us"}}

envertech-pv.0
2023-03-31 07:52:10.506	info	[REQUEST ] https://www.envertecportal.com/ApiInverters/QueryTerminalReal?page=1&perPage=20&orderBy=GATEWAYSN&whereCondition=%7B%22STATIONID%22%3A%22BD69538AB5FC4A86B419C0C7162F571E%22%7D

envertech-pv.0
2023-03-31 07:52:10.423	info	[RESPONSE] status 200 - {"Status":"0","Result":null,"Data":{"UnitCapacity":"0.9 kWp","UnitEToday":"0 kWh","UnitEMonth":"21.02 kWh","UnitEYear":"62.41 kWh","UnitETotal":"375.87 kWh","Power":0.33,"PowerStr":"0.33 W","Capacity":0.9,"StrCO2":"0.375 ton","StrTrees":"2","StrIncome":"€ 169.14","PwImg":"133212851848601888_23.png","StationName":"DaHam","InvModel1":null,"InvModel2":null,"Lat":46.77477477477478,"Lng":13.549004453344937,"TimeZone":2,"StrPeakPower":"344.09 W","Installer":"Ich","CreateTime":"27/08/2021 GMT +2","CreateYear":2021,"CreateMonth":8,"Etoday":0,"InvTotal":2}}

envertech-pv.0
2023-03-31 07:52:03.225	info	[REQUEST ] https://www.envertecportal.com/ApiStations/getStationInfo?stationId=BD69538AB5FC4A86B419C0C7162F571E

envertech-pv.0
2023-03-31 07:51:05.119	warn	[gateway] TotalCount: 2, cvtOnline:1, cvtOffline:0

envertech-pv.0
2023-03-31 07:51:05.119	warn	[gateway] inconsistent counters detected - please report to developer

envertech-pv.0
2023-03-31 07:51:04.960	info	[RESPONSE] status 200 - {"Status":"0","Result":null,"Data":{"QueryResults":[{"GATEWAYALIAS":"Enverbridge","GATEWAYSN":"94000936","SNALIAS":"Südost","SN":"20139780","DCVOLTAGE":"23.8","ACVOLTAGE":"240.63","ACCURRENCY":"0","POWER":"0.33","FREQUENCY":"50.01","DAYENERGY":"0","ENERGY":"274.63","TEMPERATURE":"13.2","SITETIME":"3/31/2023 7:50:05 AM","STATIONID":null,"STATUS":"0","SNID":"694780013BF84365AE48CB74EC2F8A28"},{"GATEWAYALIAS":"Enverbridge","GATEWAYSN":"94000936","SNALIAS":"Südwest","SN":"12893962","DCVOLTAGE":"19.25","ACVOLTAGE":"240.84","ACCURRENCY":"0","POWER":"0","FREQUENCY":"50","DAYENERGY":"0","ENERGY":"101.24","TEMPERATURE":"12.4","SITETIME":"3/31/2023 7:50:05 AM","STATIONID":null,"STATUS":"2","SNID":"8DB6DA9AF183478BB023CF4CF0CC2687"}],"PageNumber":1,"PerPage":20,"TotalPage":1,"TotalCount":2,"Lan":"en-us"}}

envertech-pv.0
2023-03-31 07:51:03.739	info	[REQUEST ] https://www.envertecportal.com/ApiInverters/QueryTerminalReal?page=1&perPage=20&orderBy=GATEWAYSN&whereCondition=%7B%22STATIONID%22%3A%22BD69538AB5FC4A86B419C0C7162F571E%22%7D

envertech-pv.0
2023-03-31 07:51:03.628	info	[RESPONSE] status 200 - {"Status":"0","Result":null,"Data":{"UnitCapacity":"0.9 kWp","UnitEToday":"0 kWh","UnitEMonth":"21.02 kWh","UnitEYear":"62.41 kWh","UnitETotal":"375.87 kWh","Power":0.33,"PowerStr":"0.33 W","Capacity":0.9,"StrCO2":"0.375 ton","StrTrees":"2","StrIncome":"€ 169.14","PwImg":"133212851848601888_23.png","StationName":"DaHam","InvModel1":null,"InvModel2":null,"Lat":46.77477477477478,"Lng":13.549004453344937,"TimeZone":2,"StrPeakPower":"344.09 W","Installer":"Ich","CreateTime":"27/08/2021 GMT +2","CreateYear":2021,"CreateMonth":8,"Etoday":0,"InvTotal":2}}

envertech-pv.0
2023-03-31 07:51:03.225	info	[REQUEST ] https://www.envertecportal.com/ApiStations/getStationInfo?stationId=BD69538AB5FC4A86B419C0C7162F571E

envertech-pv.0
2023-03-31 07:50:19.897	warn	[gateway] TotalCount: 2, cvtOnline:1, cvtOffline:0

envertech-pv.0
2023-03-31 07:50:19.896	warn	[gateway] inconsistent counters detected - please report to developer

**Comment by mcm1957** [comment] 2023-03-31 06:29
Thanks for the fast response.

The problem can/must be fixed at adaptercode. Its caused by the reported STATUS values.
STATUS = 1 indicates offline
STATUS = 0 indicates online

The EVT300 is sending STATUS = 2. Currently I do not have an idea if this is either online or offline or should be counted as seperate value.

**Could you check at website if any correlation of status=2 in http response and a displayed text like online/offline/... could be found?
Was the Inverted oprating at time of STATUS=2 (= was the sun shining?)**

I will check the earned value too of couse. 

Due do lack of time today I will provide a fix not befoire the evening or possible tomorrow.

**Comment by mcm1957** [comment] 2023-03-31 17:23
fixed with 1.0.2

**Closed** 2023-03-31 17:23 UTC
Labels: bug, fixed

**Comment by mcm1957** [comment] 2023-03-31 18:41
@JackDaniel007 
Please let me know if the problem is fixed at your site too after installing 1.0.2
Thanks

**Comment by JackDaniel007** [comment] 2023-04-03 08:15
seems to be solved, now comes only this here " host.iobroker | 2023-04-03 10:10:00.014 | warn | instance system.adapter.envertech-pv.0 already running with pid 189977 "

**Comment by mcm1957** [comment] 2023-04-03 09:51
Thats a message from js-controller. Looks like there are two instance.0 jobs running. But I'm no expert with js-controller.

If this persists even after a complete restarte / reboot of the system. please discuss at forum or open a issue at js-controller's github.
